export const CONTENT_START = "CONTENT_START";
export const CHANGE_STATUS_READ = "CHANGE_STATUS_READ";
export const CHANGE_STATUS_ERROR = "CHANGE_STATUS_ERROR";
export const CHANGE_STATUS_FINISHED = "CHANGE_STATUS_FINISHED";
export const REMOVE_FINISHED_CARDS = "REMOVE_FINISHED_CARDS";
export const CHANGE_STATUS_READ_FALSE = "CHANGE_STATUS_READ_FALSE";
