import { v4 as uuidv4 } from "uuid";
export const data = [
    {
        title: "https://img11.postila.ru/data/f3/61/36/19/f3613619145cfab893cc77380f24e4d842e0ca28bf9f4662489129719b24aec6.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://proprikol.ru/wp-content/uploads/2020/11/kartinki-personazhej-iz-multikov-24.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://www.clipartkey.com/mpngs/m/74-748521_-.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://im0-tub-ru.yandex.net/i?id=1a06443763cf29d056cf319d482f999f&n=13&exp=1",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://yesofcorsa.com/wp-content/uploads/2017/11/Mickey-Mouse-Wallpaper-For-Android.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614583060_69-p-kartinki-iz-multikov-na-belom-fone-83.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://e7.pngegg.com/pngimages/400/691/png-clipart-polar-bear-football-drawing-sport-bear-mammal-animals.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/ee/98/7a/ee987a768d4452c99e35762945364acc.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/40/b1/70/40b170c3c4f1b458d635588878095617.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://proprikol.ru/wp-content/uploads/2020/09/multyashnye-kartinki-53.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/a4/4b/a7/a44ba7d446f65a9a4932a7d22dfcd260.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://img2.freepng.ru/20190430/vae/kisspng-gadget-hackwrench-chip-n-dale-t-shirt-cartoon-pr-5cc8329fe8f1e5.7215404215566240319542.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://clipart-best.com/img/mickey-mouse/mickey-mouse-clip-art-10.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/6a/f8/2e/6af82ea6cb95db1fdc1b70f8cfcd09f3.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/736x/b5/61/cb/b561cb6ad23cde49b82c0f941412e351.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614583072_89-p-kartinki-iz-multikov-na-belom-fone-104.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://clipart-best.com/img/pluto-disney/pluto-disney-clip-art-25.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://w7.pngwing.com/pngs/53/371/png-transparent-minnie-mouse-mickey-mouse-donald-duck-daisy-duck-minnie-mouse-mouse-cartoon-fictional-character.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },

    {
        title: "https://img11.postila.ru/data/f3/61/36/19/f3613619145cfab893cc77380f24e4d842e0ca28bf9f4662489129719b24aec6.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://proprikol.ru/wp-content/uploads/2020/11/kartinki-personazhej-iz-multikov-24.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://www.clipartkey.com/mpngs/m/74-748521_-.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://im0-tub-ru.yandex.net/i?id=1a06443763cf29d056cf319d482f999f&n=13&exp=1",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://yesofcorsa.com/wp-content/uploads/2017/11/Mickey-Mouse-Wallpaper-For-Android.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614583060_69-p-kartinki-iz-multikov-na-belom-fone-83.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://e7.pngegg.com/pngimages/400/691/png-clipart-polar-bear-football-drawing-sport-bear-mammal-animals.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/ee/98/7a/ee987a768d4452c99e35762945364acc.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/40/b1/70/40b170c3c4f1b458d635588878095617.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://proprikol.ru/wp-content/uploads/2020/09/multyashnye-kartinki-53.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/a4/4b/a7/a44ba7d446f65a9a4932a7d22dfcd260.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://img2.freepng.ru/20190430/vae/kisspng-gadget-hackwrench-chip-n-dale-t-shirt-cartoon-pr-5cc8329fe8f1e5.7215404215566240319542.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://clipart-best.com/img/mickey-mouse/mickey-mouse-clip-art-10.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/originals/6a/f8/2e/6af82ea6cb95db1fdc1b70f8cfcd09f3.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://i.pinimg.com/736x/b5/61/cb/b561cb6ad23cde49b82c0f941412e351.jpg",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614583072_89-p-kartinki-iz-multikov-na-belom-fone-104.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://clipart-best.com/img/pluto-disney/pluto-disney-clip-art-25.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
    {
        title: "https://w7.pngwing.com/pngs/53/371/png-transparent-minnie-mouse-mickey-mouse-donald-duck-daisy-duck-minnie-mouse-mouse-cartoon-fictional-character.png",
        id: uuidv4(),
        statusRead: false,
        error: false,
        finished: false,
    },
];
